services:
  web:
    image: ghcr.io/cancer-complications-lifeguard-card/xiaohongka_web
    container_name: xiaohongka_web
    restart: unless-stopped
    ports:
      - "3011:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=